// Generate demo/slabs.json: the SIMULATED slab chips shared by the contracts tests, the scripts
// and the web app. Every key is a public test key, keccak256("nafuda-demo-chip:<variant>:<cert>"),
// so anyone can regenerate and check the file.
//
//   slabs  the demo titles issued by `npm run issue` (12345678, 12345679)
//   pool   slabs on the grader's bench: chips already sealed, no title yet. The grader console
//          issues titles from this pool, so every browser can tap a newly issued slab.
//
// Each slab has a genuine chip (the one the grader sealed) and a clone chip (a counterfeit slab
// printed with the same cert number).
//
//   npm run chips             check that demo/slabs.json is up to date (exit 1 if not)
//   npm run chips -- --write  rewrite it

import { readFileSync, writeFileSync } from 'node:fs'
import { keccak256, toBytes } from 'viem'
import { privateKeyToAddress } from 'viem/accounts'
import { GRADER_LABEL } from './lib.ts'

const FILE = new URL('../../demo/slabs.json', import.meta.url)

const SLABS: Record<string, [card: string, grade: string]> = {
  '12345678': ['Nafuda Dragon - Holo #001 (demo card)', 'GEM MT 10'],
  '12345679': ['Kitsune Lantern - Promo #042 (demo card)', 'MINT 9'],
}

/// Original placeholder cards, with a suggested grade the grader can change before issuing.
const POOL: Record<string, [card: string, grade: string]> = {
  '12345680': ['Tanuki Drummer - Common #107 (demo card)', 'NM-MT 8'],
  '12345681': ['Koi Ascending - Rare #013 (demo card)', 'GEM MT 10'],
  '12345682': ['Oni Blacksmith - Uncommon #066 (demo card)', 'MINT 9'],
  '12345683': ['Tengu Courier - Holo #024 (demo card)', 'NM 7'],
  '12345684': ['Maneki Guardian - Promo #001 (demo card)', 'GEM MT 10'],
  '12345685': ['Kappa Ronin - Rare #088 (demo card)', 'MINT 9'],
  '12345686': ['Crane of the Bay - Holo #031 (demo card)', 'EX-MT 6'],
  '12345687': ['Orca Lantern - Common #140 (demo card)', 'NM-MT 8'],
  '12345688': ['Baku Dreamer - Rare #057 (demo card)', 'MINT 9'],
  '12345689': ['Raijin Spark - Secret #099 (demo card)', 'GEM MT 10'],
}

function chip(variant: 'genuine' | 'clone', cert: string) {
  const privateKey = keccak256(toBytes(`nafuda-demo-chip:${variant}:${cert}`))
  return { privateKey, address: privateKeyToAddress(privateKey) }
}

const slabs = (entries: Record<string, [string, string]>) =>
  Object.fromEntries(
    Object.entries(entries).map(([cert, [card, grade]]) => [cert, { card, grade, genuine: chip('genuine', cert), clone: chip('clone', cert) }]),
  )

const json = `${JSON.stringify(
  {
    _note:
      "SIMULATED chips for the hackathon demo. These private keys are public test keys derived as keccak256('nafuda-demo-chip:<variant>:<cert>'). A real chip keeps its key inside the slab and never exposes it. Generated by scripts/src/chips.ts.",
    grader: GRADER_LABEL,
    slabs: slabs(SLABS),
    pool: slabs(POOL),
  },
  null,
  2,
)}\n`

if (process.argv.includes('--write')) {
  writeFileSync(FILE, json)
  console.log(`wrote ${Object.keys(SLABS).length} demo slabs and ${Object.keys(POOL).length} pool slabs`)
} else if (readFileSync(FILE, 'utf8') === json) {
  console.log('demo/slabs.json is up to date')
} else {
  console.error('demo/slabs.json differs from the generator: run `npm run chips -- --write`')
  process.exit(1)
}
