// Demo collectors: who holds and trades titles in the demo. Writes demo/collectors.json
// (names, bios and public addresses only; never keys).
//
//   alice, bob, mallory   the original demo accounts (ALICE_PK, BOB_PK, MALLORY_PK)
//   aiko … priya          derived from DEMO_MNEMONIC (addressIndex 0–11)
//   sololin               the author's own test wallet (external: its key is not in .env)
//
//   node --env-file=../.env src/collectors.ts            check demo/collectors.json
//   node --env-file=../.env src/collectors.ts --write    rewrite it

import { readFileSync, writeFileSync } from 'node:fs'
import { getAddress, type Address, type Hex, type PrivateKeyAccount } from 'viem'
import { mnemonicToAccount, privateKeyToAccount } from 'viem/accounts'

export type Collector = { name: string; bio: string; address: Address; source: 'env' | 'mnemonic' | 'external'; index?: number }

const PERSONAS: [name: string, bio: string][] = [
  ['aiko', 'Tokyo. Chases vintage holos from the Yokai Parade set.'],
  ['kenji', 'Runs a small card shop in Osaka; buys at every show.'],
  ['yuki', 'Sapporo. Only collects GEM MINT, only Secrets.'],
  ['haruto', 'Student in Kyoto, trading up one slab at a time.'],
  ['sakura', 'Nagoya. Completes sets, one of each rarity.'],
  ['ren', 'Fukuoka. Flips slabs between weekend shows.'],
  ['mika', 'Yokohama. Collects anything with a fox on it.'],
  ['taro', 'Sendai. Long-term holder; rarely sells.'],
  ['emma', 'Visiting from London for the Tokyo show.'],
  ['liam', 'Sydney. Buys Japanese promos at shows abroad.'],
  ['chen', 'Taipei. Crosses over for the big Tokyo events.'],
  ['priya', 'Singapore. Focused on BGS pristine slabs.'],
]

const ENV_ACCOUNTS: [name: string, bio: string, key: string][] = [
  ['alice', 'The first collector: submitted the first two demo slabs.', 'ALICE_PK'],
  ['bob', 'Buyer in the demo walk-through.', 'BOB_PK'],
  ['mallory', 'Shows up with genuine slabs but not the titles.', 'MALLORY_PK'],
]

export const AUTHOR = { name: 'sololin', bio: 'The builder of Nafuda. Holds a few titles to demo with a real wallet.', address: getAddress('0x192Fe9ee6b82B6a5c2C1bE9A7eE89EAc91D38240') }

/// Signing accounts for everyone whose key is available (env keys and the mnemonic).
export function collectorAccounts(env = process.env): Record<string, PrivateKeyAccount | ReturnType<typeof mnemonicToAccount>> {
  const out: Record<string, PrivateKeyAccount | ReturnType<typeof mnemonicToAccount>> = {}
  for (const [name, , key] of ENV_ACCOUNTS) if (env[key]) out[name] = privateKeyToAccount(env[key] as Hex)
  const mnemonic = env.DEMO_MNEMONIC
  if (mnemonic) PERSONAS.forEach(([name], i) => (out[name] = mnemonicToAccount(mnemonic, { addressIndex: i })))
  return out
}

export function collectors(env = process.env): Collector[] {
  const accounts = collectorAccounts(env)
  const list: Collector[] = []
  for (const [name, bio] of ENV_ACCOUNTS) if (accounts[name]) list.push({ name, bio, address: accounts[name].address, source: 'env' })
  PERSONAS.forEach(([name, bio], i) => {
    if (accounts[name]) list.push({ name, bio, address: accounts[name].address, source: 'mnemonic', index: i })
  })
  list.push({ ...AUTHOR, source: 'external' })
  return list
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const file = new URL('../../demo/collectors.json', import.meta.url)
  const list = collectors()
  if (list.length !== ENV_ACCOUNTS.length + PERSONAS.length + 1) throw new Error('missing keys: set ALICE_PK, BOB_PK, MALLORY_PK and DEMO_MNEMONIC')
  const json = `${JSON.stringify({ _note: 'Demo collectors: public names, bios and addresses only. Generated by scripts/src/collectors.ts.', collectors: list }, null, 2)}\n`
  if (process.argv.includes('--write')) {
    writeFileSync(file, json)
    console.log(`wrote ${list.length} collectors`)
  } else if (readFileSync(file, 'utf8') === json) {
    console.log('demo/collectors.json is up to date')
  } else {
    console.error('demo/collectors.json differs: run with --write')
    process.exit(1)
  }
}
