// Render docs/deployments.md from deployments/sepolia.json.
//
//   npm run report

import { writeFileSync } from 'node:fs'
import { beta, UNIVERSAL_RESOLVER } from './addresses.ts'
import { GRADER_LABEL, demoSlabs, loadState } from './lib.ts'

const nameLabel = process.env.NAME_LABEL ?? 'nafuda'
const state = loadState('sepolia', nameLabel)
const scan = (kind: 'address' | 'tx', v: string) => `[\`${v}\`](https://sepolia.etherscan.io/${kind}/${v})`
const root = `${nameLabel}.eth`
const grader = `${GRADER_LABEL}.${root}`

const lines = [
  '# Sepolia deployment',
  '',
  `Generated by \`npm run report\` from \`deployments/sepolia.json\`. Network: Sepolia, ENSv2 Beta (official deployment of 2026-09-15, contracts-v2 @ 71a3b733).`,
  '',
  '## Names',
  '',
  '| Name | What it is |',
  '|---|---|',
  `| \`${root}\` | Nafuda root name, registered through the official \`ETHRegistrar\` |`,
  `| \`${grader}\` | PSA-Sim, the simulated grader. Its resolver is \`TitleController\`, which answers for every cert below it (wildcard) |`,
  ...Object.entries(demoSlabs()).map(([cert, s]) => `| \`${cert}.${grader}\` | Demo title: ${s.card}, ${s.grade} |`),
  ...Object.values(state.graders ?? {})
    .filter((g) => g.label !== GRADER_LABEL)
    .map((g) => `| \`${g.label}.${root}\` | ${g.name.split(' (')[0]}, a simulated grader added in v3. Resolver: its own controller (v${g.controllerVersion}) |`),
  `| \`<collector>.${root}\` | Demo collectors' names (v3), resolved by an official ENSv2 PermissionedResolver; each collector's primary name points back |`,
  '',
  '## Contracts deployed by Nafuda',
  '',
  '| Contract | Address |',
  '|---|---|',
  `| \`nafudaRegistry\` (UserRegistry proxy for \`${root}\`) | ${scan('address', state.nafudaRegistry!)} |`,
  `| \`psaRegistry\` (UserRegistry proxy for \`${grader}\`, emancipated) | ${scan('address', state.psaRegistry!)} |`,
  `| \`TitleController\` | ${scan('address', state.titleController!)} |`,
  ...Object.values(state.graders ?? {})
    .filter((g) => g.label !== GRADER_LABEL)
    .flatMap((g) => [
      `| \`${g.label}\` registry (UserRegistry proxy, emancipated) | ${scan('address', g.registry)} |`,
      `| \`${g.label}\` controller (TitleController${g.controllerVersion === 2 ? 'V2' : ''}) | ${scan('address', g.controller)} |`,
    ]),
  ...((state as { collectorResolver?: string }).collectorResolver
    ? [`| Collector names resolver (PermissionedResolver proxy) | ${scan('address', (state as { collectorResolver?: string }).collectorResolver!)} |`]
    : []),
  '',
  '## Official ENSv2 Beta contracts used',
  '',
  '| Contract | Address |',
  '|---|---|',
  ...(['ETHRegistry', 'ETHRegistrar', 'VerifiableFactory', 'UserRegistryImpl', 'MockUSDC'] as const).map(
    (n) => `| ${n} | ${scan('address', beta(n).address)} |`,
  ),
  `| Universal Resolver (proxy) | ${scan('address', UNIVERSAL_RESOLVER())} |`,
  '',
  '## Transactions',
  '',
  '| Step | Transaction |',
  '|---|---|',
  ...Object.entries(state.txs).map(([step, hash]) => `| ${step} | ${scan('tx', hash)} |`),
  '',
]

writeFileSync(new URL('../../docs/deployments.md', import.meta.url), lines.join('\n'))
console.log('wrote docs/deployments.md')
